interface handler {
    use jabratech:common/types.{response};
    use types.{live-positions-risk-request, live-positions-risk-response};

    get-live-positions-risk: func(request: live-positions-risk-request) -> result<live-positions-risk-response, response>;
}